services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      VITE_APP_API_BASE: "http://nginx/api"
      VITE_APP_API_AUTH: "http://nginx/api/auth"
      VITE_APP_OPEN_API_HOST: "nginx"
      VITE_APP_OPEN_API_PORT: "80"
      VITE_APP_OPENAPI_PROTOCOL: "http"
    networks:
      - net-twittix

networks:
  net-twittix:
    external: true