name: CI/CD Twittix Front User

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Generate API client
        run: npm run openapi:local

      - name: Create .env file for production
        run: |
          echo "VUE_APP_API_BASE=${{ secrets.API_URL }}" >> .env
          echo "VUE_APP_API_AUTH=${{ secrets.API_AUTH_URL }}" >> .env
          echo "VUE_APP_OPEN_API_HOST=${{ secrets.OPENAPI_URL }} " >> .env
          echo "VUE_APP_OPEN_API_PORT=${{ secrets.OPENAPI_PORT }}" >> .env
          echo "VUE_APP_OPENAPI_PROTOCOL=http" >> .env

      - name: Build the app
        run: npm run build

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: front-artifacts
          path: |
            dist/
            compose.yml
            Dockerfile

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: front-artifacts
          path: ./

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/twittix-front-user:latest
