name: CI/CD Twittix Front User

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Generate API client
        run: npm run openapi:local

      - name: Create .env file for production
        run: |
          echo "VUE_APP_API_BASE=${{ secrets.API_URL }}" >> .env
          echo "VUE_APP_API_AUTH=${{ secrets.API_AUTH_URL }}" >> .env
          echo "VUE_APP_OPEN_API_HOST=${{ secrets.OPENAPI_URL }} " >> .env
          echo "VUE_APP_OPEN_API_PORT=${{ secrets.OPENAPI_PORT }}" >> .env
          echo "VUE_APP_OPENAPI_PROTOCOL=http" >> .env

      - name: Build the app
        run: npm run build

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: front-artifacts
          path: |
            dist/
            Dockerfile
            nginx.conf

  # build/deploy:
  #   runs-on: ubuntu-latest
  #   needs: test

  #   - name: Download dist folder
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: front-artifacts
  #         path: ./

  #   - name: Get short SHA
  #     run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_ENV

  #   - name: Print short SHA
  #     run: echo "Short SHA is ${{ env.SHORT_SHA }}"

  #   steps:
  #     - name: Set short git commit SHA
  #       id: vars
  #       run: |
  #         calculatedSha=$(git rev-parse --short ${{ github.sha }})
  #         echo "SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

  #     - name: "gcr.io/cloud-builders/docker"
  #       args: ['build', '-t', 'gcr.io/$PROJECT_ID/twittix/front-user:${{ env.SHORT_SHA }}', '.']

  #     - name: "gcr.io/cloud-builders/docker"
  #       args: ["push", 'gcr.io/$PROJECT_ID/twittix/front-user:${{ env.SHORT_SHA }}']

  #     - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  #       entrypoint: "gcloud"
  #       args:
  #         [
  #           "run", "deploy", "auth-api",
  #           "--image", "gcr.io/$PROJECT_ID/twittix/front-user:${{ env.SHORT_SHA }}'",
  #           "--region", "europe-west1",
  #           "--platform", "managed",
  #           "--allow-unauthenticated"
  #         ]
